### ISSUE TITLE
discrepancies between dbdd and dbdd_predict (or dbdd_predict_diag)

### ISSUE THREAD

**Issue by nguyen-tuonghuy** [lducas/leaky-LWE-Estimator#7]
Hello,

While running the LWE-leaky-estimator without using any hints (i.e. just following the README and playing around parameters), I found that initializing and using the estimate_attack method does not yield the same estimated $\beta$ depending on the initialization  with DBDD or DBDD_predict or DBDD_predict_diag. Mainly, during my experiments, I found out that DBDD_predict and DBDD_predict_diag recover the same $\beta$ whereas it could happen that DBDD recovers a much smaller $\beta$. 

Such an instance:
```
n = 1400
q = 2**24
m = n
Xs = build_centered_binomial_law(80)
Xe = Xs
_, _, dbdd_full = initialize_from_LWE_instance(DBDD, n, q, m, Xe, Xs, verbosity=2)
_, _ = dbdd_full.estimate_attack()
```
This initialization leads to (beware, it takes several minutes to initialize):
```
sage: _, _ = dbdd_full.estimate_attack()
       Attack Estimation      
 ln(dvol)=22310.1687263 	 ln(Bvol)=27474.5999621 	 ln(Svol)=10328.8624715 	δ(β)=1.002983 
 dim=2801 	 δ=1.002983 	 β=600.87
```

Whereas, using DBDD_predict (or DBDD_predict_diag) by initializing:
```
_, _, dbdd_predict = initialize_from_LWE_instance(DBDD_predict, n, q, m, Xe, Xs, verbosity=2)
_, _ = dbdd_predict.estimate_attack()
```
I would get:
```
sage: _, _ = dbdd_predict.estimate_attack()
       Attack Estimation      
 ln(dvol)=18125.3140311 	 ln(Bvol)=23289.7452668 	 ln(Svol)=10328.8624715 	δ(β)=1.002491 
 dim=2801 	 δ=1.002491 	 β=768.03  

``` 
or 
```
sage: _, _ = dbdd_predict_diag.estimate_attack()
       Attack Estimation      
 ln(dvol)=18125.3140311 	 ln(Bvol)=23289.7452668 	 ln(Svol)=10328.8624715 	δ(β)=1.002491 
 dim=2801 	 δ=1.002491 	 β=768.03  
```

For comparison, here's what the "lattice-estimator" would yields on the same parameters set:
```
sage: from estimator import *
sage: Xs = ND.CenteredBinomial(80)
sage: Xe = ND.CenteredBinomial(80)
sage: n=1400
sage: q=2**24
sage: test = LWE.Parameters(n=n, q=q, Xs=Xs, Xe=Xe,m=n)
sage: LWE.primal_usvp(test)
rop: ≈2^246.8, red: ≈2^246.8, δ: 1.002488, β: 769, d: 2787, tag: usvp
```

My question: is it normal that DBDD recovers a much smaller $\beta$ than the other faster instances DBDD_predict and DBDD_predict_diag ?

Thank you !

**Comment by lducas** [comment]
It appears that they diverge on the computation of `log(volB)'. 
The correct value is `1400 * ln(2^24) = 23289.7' matching `dbdd_predict'. 
I suspect a numerical stability issue for determinant computation of such a large matrix (2800x2800 !). `dbdd_predict" avoid such issues because it does not compute such a determinant but merely predict it.

Do you have a usecase for  `dbdd' for such a large dimension, or would dbdd_predict be sufficient for your purpose ? It was certainly not designed with this case in mind. Each hint is going to take minutes if not hours to process. 
I am asking in case there is no good fix, wether I might simply throw a warning/error for large dimension `dbdd'.

**Comment by nguyen-tuonghuy** [comment]
Thank you for your quick answer. 

I have no particular usecase for dbdd in such large dimension, except fiddling around with some parameters sets. Initially, my goal was to compare the estimated $\beta$ with those recover by the "lattice-estimator" (in small dimensions where the methodologies differ). Then I tried some higher dimension instances and found this issue (even though the methodologies would not differ in those range, if I'm not mistaken).

In any case, I think a warning would be enough.

**Comment by lducas** [comment]
`dbdd_predict_diag` should be more than enough for that purpose indeed.

The following option should also allow to match the new estimator "CN11" simulator (usvp attack):
`estimate_attack(probabilistic=True)`

Though you might have yo tweak the following to trade-off feasibility VS precision. For large parameter you can simply set ``estimate_attack(probabilistic=True, ignore_lift_proba=True`)
